<a href="https://colab.research.google.com/github/DelightValerie/Tensors/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip list

Tensor: multi-dimentional matrix containing elemets of a single data type

Default data type of float32

In [ ]:
import torch
import numpy as np

LISTS

In [ ]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NUMPY ARRAYS

In [ ]:
np1 = np.random.rand(3,4,)
np1

array([[0.42490751, 0.85056281, 0.46293436, 0.0681906 ],
       [0.1316777 , 0.32926152, 0.91877949, 0.98440169],
       [0.85895206, 0.31945785, 0.52956341, 0.7840487 ]])

In [ ]:
np1.dtype

dtype('float64')

TENSORS

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype (tensors are by default )

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#create tensor from numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4249, 0.8506, 0.4629, 0.0682],
        [0.1317, 0.3293, 0.9188, 0.9844],
        [0.8590, 0.3195, 0.5296, 0.7840]], dtype=torch.float64)