<a href="https://colab.research.google.com/github/DelightValerie/Tensors/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSOR OPERATIONS: Reshape and Slice

In [ ]:
import torch

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#Throws an error because (3,5) doesn't shape up with 10
my_torch = my_torch.reshape(3,5)
my_torch

RuntimeError: shape '[3, 5]' is invalid for input of size 10

In [ ]:
#Reshape if you don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [ ]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
my_torch13 = torch.arange(24)
my_torch13

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [ ]:
my_torch13 = my_torch13.reshape(-1,12)
my_torch13

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

DIFFERENCES BETWEEN RESHAPE AND VIEW

https://pytorch.org/docs/stable/generated/torch.reshape.html

https://pytorch.org/docs/stable/tensor_view.html

https://discuss.pytorch.org/t/whats-the-difference-between-torch-reshape-vs-torch-view/159172



In [ ]:
#with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

SLICES

Allow you to grab a session of your tensor

In [ ]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Grab specific item
my_torch7[7]

tensor(7)

In [ ]:

my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
#Grab slice
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
my_torch8[:,0]

tensor([0, 2, 4, 6, 8])

In [ ]:
#Grab column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])