<a href="https://colab.research.google.com/github/DelightValerie/Tensors/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSOR MATH OPERATIONS
*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and Longhand
*   Reassignment



In [110]:
import torch
import numpy as np

In [111]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

Shorthand

In [112]:
#Addition (shorthand)
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [113]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [114]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [115]:
#Division
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [116]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [117]:
#Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [118]:
#Exponent/Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

Longhand

In [119]:
#Addition
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [120]:
#Addition Method2
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [121]:
#Subtraction
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [122]:
#Multiplication
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [123]:
#Division
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [124]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [125]:
#Remainder Modulus
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [126]:
#Exponent/Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

Reassignment

In [127]:
#Reassignment using_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [128]:
tensor_a

tensor([1, 2, 3, 4])

In [129]:
tensor_b

tensor([5, 6, 7, 8])

In [130]:
tensor_a.mul_(tensor_b)

tensor([ 5, 12, 21, 32])

In [131]:
tensor_a

tensor([ 5, 12, 21, 32])

In [134]:
tensor_a.add_(tensor_b)

tensor([10, 18, 28, 40])

In [135]:
tensor_a

tensor([10, 18, 28, 40])